=== skitskattt/WebEngineeringProblem2/Mensaplan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:Mensa.Namespace" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mensa" type="urn:mensaType" xmlns:urn="urn:Mensa.Namespace"/>
  <xs:complexType name="gerichtType">
    <xs:sequence>
      <xs:element name="name"/>
      <xs:element name="ausgabe" minOccurs="0"/>
      <xs:element name="student"/>
      <xs:element name="mitarbeiter"/>
      <xs:element name="gast"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="gerichtTypType">
    <xs:sequence>
      <xs:element name="typname" />
      <xs:element type="urn:gerichtType" name="gericht" maxOccurs="unbounded" minOccurs="0" xmlns:urn="urn:Mensa.Namespace"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="gerichteType">
    <xs:sequence>
      <xs:element type="urn:gerichtTypType" name="gerichtTyp" maxOccurs="unbounded" minOccurs="0" xmlns:urn="urn:Mensa.Namespace"/>
      <xs:element type="urn:salateDessertsType" name="salateDesserts" xmlns:urn="urn:Mensa.Namespace"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="salateDessertsType">
    <xs:sequence>
      <xs:element type="xs:string" name="typname"/>
      <xs:element type="xs:string" name="beschreibung"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="stralsundSpeiseplanType">
    <xs:sequence>
      <xs:element type="xs:string" name="date"/>
      <xs:element type="xs:string" name="geschaeftsZeiten"/>
      <xs:element type="urn:gerichteType" name="gerichte" xmlns:urn="urn:Mensa.Namespace"/>
      <xs:element type="urn:salateDessertsType" name="salateDesserts" xmlns:urn="urn:Mensa.Namespace"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id"/>
  </xs:complexType>
  
  <xs:complexType name="mensaType">
    <xs:sequence>
      <xs:element type="urn:stralsundSpeiseplanType" name="stralsundSpeiseplan" xmlns:urn="urn:Mensa.Namespace"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== skitskattt/WebEngineeringProblem2/Mensaplan.xml
<?xml version="1.0" encoding="UTF-8" ?>

<mensa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="urn:Mensa.Namespace Mensaplan.xsd"
       xmlns="urn:Mensa.Namespace">

        <stralsundSpeiseplan id="19122022">
                <date>19.12.2022</date>

                <geschaeftsZeiten>
                    ÖZ: 11.15 - 13.45,
                    ÖZ - Cafeteria: 8.00 - 14.00
                </geschaeftsZeiten>
                <gerichte>
                    <gerichtTyp>
                        <typname>Tellergericht</typname>
                        <gericht>
                            <name>Brötchen</name>
                            <ausgabe>Veg</ausgabe>
                            <student>0,45€</student>
                            <mitarbeiter>0,60€</mitarbeiter>
                            <gast>0,60€</gast>
                        </gericht>

                        <gericht>
                            <name>4 Hefeklöße mit Fruchtsoße</name>
                            <ausgabe>Veg</ausgabe>
                            <student>1,80€</student>
                            <mitarbeiter>3,00€</mitarbeiter>
                            <gast>4,30€</gast>
                        </gericht>
                    </gerichtTyp>

                    <gerichtTyp>
                        <typname>Komponente 1</typname>
                        <gericht>
                            <name>Schlemmerfilet Brokkoli Käse</name>
                            <ausgabe>1</ausgabe>
                            <student>2,25€</student>
                            <mitarbeiter>3,10€</mitarbeiter>
                            <gast>3,05€</gast>
                        </gericht>
                    </gerichtTyp>

                    <gerichtTyp>
                        <typname>Komponente 2</typname>
                        <gericht>
                            <name>Jagdwurstgulasch</name>
                            <ausgabe></ausgabe>
                            <student>2,25€</student>
                            <mitarbeiter>3,10€</mitarbeiter>
                            <gast>3,95€</gast>
                        </gericht>
                    </gerichtTyp>

                    <gerichtTyp>
                        <typname>Vegetarisch oder Vegan</typname>
                        <gericht>
                            <name>Vegan ; Gemüseschnitte , Tomatensauce , Reis</name>
                            <ausgabe>Veg</ausgabe>
                            <student>2,10€</student>
                            <mitarbeiter>3,30€</mitarbeiter>
                            <gast>4,60€</gast>
                        </gericht>
                    </gerichtTyp>

                    <gerichtTyp>
                        <typname>Pasta nach Gewicht (Preis pro 100 g)</typname>
                        <gericht>
                            <name>Pastateller: Spiralen</name>
                            <ausgabe></ausgabe>
                            <student>0,60€</student>
                            <mitarbeiter>0,90€</mitarbeiter>
                            <gast>1,20€</gast>
                        </gericht>
                    </gerichtTyp>

                    <gerichtTyp>
                        <typname>Beilagen</typname>
                        <gericht>
                            <name>Salzkartoffeln</name>
                            <ausgabe>1, 2</ausgabe>
                            <student>0,70€</student>
                            <mitarbeiter>1,00€</mitarbeiter>
                            <gast>1,40€</gast>
                        </gericht>
                        <gericht>
                            <name>Spiralen</name>
                            <ausgabe>1</ausgabe>
                            <student>0,70€</student>
                            <mitarbeiter>1,00€</mitarbeiter>
                            <gast>1,40€</gast>
                        </gericht>
                        <gericht>
                            <name>Kräuterreis</name>
                            <student>0,70€</student>
                            <mitarbeiter>1,00€</mitarbeiter>
                            <gast>1,40€</gast>
                        </gericht>
                    </gerichtTyp>

                    <gerichtTyp>
                        <typname>Gemüse</typname>
                        <gericht>
                            <name>Grüne Bohnengemüse</name>
                            <student>0,70€</student>
                            <mitarbeiter>1,00€</mitarbeiter>
                            <gast>1,40€</gast>
                        </gericht>

                        <gericht>
                            <name>Buntes Möhrengemüse</name>
                            <ausgabe>1, 2</ausgabe>
                            <student>0,70€</student>
                            <mitarbeiter>1,00€</mitarbeiter>
                            <gast>1,40€</gast>
                        </gericht>
                    </gerichtTyp>

                    <gerichtTyp>
                        <typname>Gemüse</typname>
                        <gericht>
                            <name>Grüne Bohnengemüse</name>
                            <student>0,70€</student>
                            <mitarbeiter>1,00€</mitarbeiter>
                            <gast>1,40€</gast>
                        </gericht>

                        <gericht>
                            <name>Buntes Möhrengemüse</name>
                            <ausgabe>1, 2</ausgabe>
                            <student>0,70€</student>
                            <mitarbeiter>1,00€</mitarbeiter>
                            <gast>1,40€</gast>
                        </gericht>
                    </gerichtTyp>
                    

                    <salateDesserts>
                        <typname>Salate und Desserts</typname>
                        <beschreibung>
                            Frische Salate und verschiedene Desserts stehen zur Auswahl.
                        </beschreibung>
                    </salateDesserts>



                </gerichte>

        </stralsundSpeiseplan>
</mensa>
